-- Exercise 2: Aggregate Functions

SELECT * FROM PETRESCUE;

SELECT SUM(COST) FROM PETRESCUE;

SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;

SELECT MAX(QUANTITY) FROM PETRESCUE;

SELECT AVG(COST) FROM PETRESCUE;

SELECT AVG(COST) FROM PETRESCUE WHERE ANIMAL = 'Dog';

-- Exercise 3: Scalar and String Functions --

SELECT ROUND(COST) FROM PETRESCUE;

SELECT LENGTH(ANIMAL) FROM PETRESCUE;

SELECT UCASE(ANIMAL) FROM PETRESCUE;

SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL) = 'cat';

-- Exercise 4 Solutions: Date and Time Functions --

SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'Cat';

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE)='05';

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE)='14';

SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE;

SELECT (CURRENT DATE - RESCUEDATE) FROM PETRESCUE;